version: "2.1"

services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    depends_on:
      namenode:
        condition: service_healthy
    ports:
      - "50075:50075"
  spark-master:
    build: ./master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - ./hadoop-hive.env
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy
  spark-worker:
    build: ./worker
    container_name: spark-worker
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop-hive.env
    depends_on:
      spark-master:
        condition: service_healthy

